# docker-compose.yml
version: '3.7'
services:
  backend1:
    container_name: tools-serv1
    image: tools-app:1.0.0
    ports:
      - 8081:8081
      - 11112:11111
    depends_on:
      - postgres
    links:
      - postgres
    networks:
      - postgres-network

  ###### Database
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
      POSTGRES_DB: tools
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres-network
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres-network
    restart: unless-stopped


networks:
  postgres:
    driver: bridge
volumes:
  postgres:
  pgadmin:

#version: "3.7"
#services:
#  rabbitmq:
#    image:  rabbitmq:3-management
#    container_name: some-rabbit11
#    ports:
#      - 5671-5672:5671-5672
#      - 15672:15672
#    networks:
#      - backend
#
#  backend1:
#    container_name: backend1
#    image: com.master/backend1:latest
#    ports:
#      - 8082:8080
#      - 11112:11111
#    depends_on:
#      - rabbitmq
#    links:
#      - rabbitmq
#    networks:
#      - backend
#
#  backend-reader:
#    container_name: backend-reader
#    image: com.master/backend-reader:latest
#    ports:
#      - 8084:8083
#      - 11113:11111
#    depends_on:
#      - rabbitmq
#    links:
#      - rabbitmq
#    networks:
#      - backend
#
