# docker-compose.yml
version: '3.7'
services:
  tools:
    environment:
      - DATABASE_HOST_IP=postgres
    container_name: tools-app
    image: tools-app:1.0.0
    ports:
      - 8082:8082
      - 11112:11111
    depends_on:
      - postgres
    links:
      - postgres
    networks:
      - postgres-network

  gateway:
    container_name: gateway-app
    image: api-gateway:1.0.0
    ports:
      - 8095:8095
    depends_on:
      - tools
      - orders
      - postgres
#    links:
#      - tools
#      - orders
#      - postgres
    networks:
      - postgres-network

  orders:
    container_name: orders-app
    image: orders-app:1.0.0
    ports:
      - 8083:8083
    depends_on:
      - postgres
    links:
      - postgres
    networks:
      - postgres-network

  ###### Database
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
      POSTGRES_DB: tools
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - postgres-network
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - 5050:5050
    networks:
      - postgres-network
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres

networks:
  postgres-network:
    driver: bridge
volumes:
  postgres:
  pgadmin:
